services:
  redis:
    image: redis:7-alpine
    container_name: heatmap-redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - app-network

  node-api:
    image: ghcr.io/sandrogaliazzi/heatmap-backend:latest
    container_name: heatmap-backend
    ports:
      - "5005:5005"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
    restart: always
    depends_on:
      - redis
    volumes:
      - ./backend/images:/app/images
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/24"
          gateway: 172.25.0.1