services:
  node-api:
    image: ghcr.io/sandrogaliazzi/heatmap-backend:latest
    container_name: heatmap-backend
    ports:
      - "5005:5005"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - ./backend/images:/app/images
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/24"
          gateway: 172.25.0.1