services:
  node-api:
    build: ./backend
    ports:
      - "5005:5005"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: always
    networks:
      app-network:

  vue-app:
    build: ./frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - PORT=5000
    stdin_open: true
    tty: true
    depends_on:
      - node-api
    restart: always
    networks:
      app-network:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/24"
          gateway: 172.25.0.1
