services:
  node-api:
    build: ./backend
    ports:
      - "5005:5005"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      app-network:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.25.0.0/24"
          gateway: 172.25.0.1
