name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar sshpass
        run: sudo apt-get install sshpass

      - name: Acessar o servidor e configurar sudo sem senha
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Adicionando a permissão para o usuário sem senha
            echo "$USER ALL=(ALL) NOPASSWD: ALL" | sudo tee /etc/sudoers.d/${{ secrets.SSH_USER }}
            cd heatmap-full/heatmap-full/
            git pull origin main
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
