name: Auto Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar sshpass
        run: sudo apt-get install sshpass

      - name: Acessar o servidor e atualizar a aplicação
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd heatmap-full/heatmap-full/
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
